# Generated by Django 4.2.1 on 2023-05-13 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_noticia_resultado_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='noticias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.noticia'),
        ),
    ]
