# Generated by Django 4.1.9 on 2023-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_resultado_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
