# Generated by Django 4.1.9 on 2023-05-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_noticia_link_alter_resultado_titulo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
        migrations.AlterModelTable(
            name='resultado',
            table='resultado-analise',
        ),
    ]
